spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/cidade-segura"
    password: puc@2015
    username: postgres
    driver-class-name: org.postgresql.Driver
  #datasource:
    #url: jdbc:h2:~/pedidos
    #password: root
    #driver-class-name: org.h2.Driver
    #h2:
     # console:
      #  enabled: true
       # path: /h2
  jpa:
    ddl-auto: create
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

